### ISSUE TITLE
upgrade vue to v3 in vue-apollo tutorial

### ISSUE THREAD

**Issue by praveenweb** [hasura/learn-graphql#189]
The current vue-apollo tutorial uses Vue stable version 2.x. Now that Vue has reached beta v3, we can update the tutorial to support necessary changes like using Composition API (if required) etc.

**Comment by namoscato** [comment]
Hey, @praveenweb! I had a chance to start on this (https://github.com/hasura/learn-graphql/compare/master...namoscato:vue-3) but wanted to sync before getting too far along. A few immediate questions:

1. Is there a preferred way to go about the tutorial updates to facilitate reviews? I haven't gotten too far past updating the boilerplate setup and am unsure how much of the actual tutorial will need to be updated.
1. Should [Prettier](https://prettier.io/) be enabled / auto-fixed for the sample project? (I ask because Vue CLI auto-installed it when I upgraded.)

> like using Composition API (if required)

Given this is [additive / optional](https://v3.vuejs.org/guide/migration/introduction.html#introduction), it might make sense to ignore this, at least for the first pass?

I might not be able to finish these updates in the near future depending on how involved they are but can hopefully help!

**Comment by praveenweb** [comment]
@namoscato - Hi, thanks for attempting to do a v1 of this.

Vue 3 stable has been released and as a first step, we can do a basic migration to get things working for version 1. As far as the tutorial is concerned, it is more about using GraphQL inside Vue than learning Vue (or Vue 3 concepts). The new changes would most likely be code snippets which were part of the migration.

Let me know if you would like to take this up and I'm happy to help.

**Comment by namoscato** [comment]
@praveenweb, sounds good. Not sure what your timeline looks like, but I could probably take a pass through the rest of this within the next couple of weeks.

**Comment by namoscato** [comment]
FYI [vue-apollo](https://github.com/vuejs/vue-apollo) does not fully support Vue 3 yet (i.e. there is an alpha, but it's not tagged yet), so it probably makes sense to wait on this.
