### ISSUE TITLE
HASURA-AUTH-SLACK: INFO config v1 is deprecated from v1.4, FATA[0001] please upgrade your project to a newer version.

### ISSUE THREAD

**Issue by m4ttheweric** [hasura/learn-graphql#495]
I am going through the HASURA-AUTH-SLACK tutorial. When I get to the [apply migrations step](https://hasura.io/learn/graphql/hasura-auth-slack/data-modelling/3-apply-migrations/) I am encountering an error. 

Repro steps:

1. Download the migrations from [here](https://hasura.io/learn/graphql/hasura-auth-slack/slack-backend.zip)
2. Modified the ``config.yaml`` to match my app. Config ended up like this: 
```
endpoint: https://precious-snail-63.hasura.app
admin_secret: xxx
```
3. Opened a terminal window at the directory of the downloaded migrations folder containing the ``config.yaml`` and ran the command ``hasura migrate apply`` per the instructions in the tutorial.

Get the following output:

```
INFO config v1 is deprecated from v1.4
FATA[0001] please upgrade your project to a newer version.
use hasura scripts update-project-v2 to upgrade your project to config v2 
```

4. Following the above output, I run the command ``hasura scripts update-project-v2`` in the same dir. The output is as follow: 

```
INFO migrations are backed up to migrations_backup directory. 
FATA[0002] unable to initialize migrations driver: cannot create migrate instance: {
  "internal": {
    "statement": "CREATE TABLE hdb_catalog.schema_migrations (version bigint not null primary key, dirty boolean not null)",
    "prepared": false,
    "error": {
      "exec_status": "FatalError",
      "hint": null,
      "message": "schema \"hdb_catalog\" does not exist",
      "status_code": "3F000",
      "description": null
    },
    "arguments": []
  },
  "path": "$",
  "error": "query execution failed",
  "code": "postgres-error"
} 
```

At this point I am dead in the water as to what to do next. 

Am I running these commands from the correct directory? I am very new to hasura and just trying to get oriented using the tutorial so I am a little green.

**Comment by praveenweb** [comment]
Hey @m4ttheweric 

Sorry about your onboarding experience. The project migrations and metadata being used in the tutorial were made for versions prior to Hasura v2 and hence there are inconsistencies when you are trying to apply these to the latest version of Hasura.

I have made the necessary fixes to the tutorial in this PR - https://github.com/hasura/learn-graphql/pull/500.

Request you to re-download the `slack-backend.zip` file again, since the directory structure has changed. I will be triggering a deployment soon to merge the content changes to the tutorial on the UI.

The new instructions should work seamlessly for you. Let me know if it goes otherwise.

**Comment by m4ttheweric** [comment]
@praveenweb Thank you SO much for this quick response. Very much appreciated.

**Comment by SenchaMacha** [comment]
C:\hasura-todo-YT\reactathon-workshop\hasura> hasura migrate apply 

INFO config v1 is deprecated from v1.4
 level=fatal msg="please upgrade your project to a newer version
@praveenweb how do i fix this?
