### ISSUE TITLE
Getting SyntaxError when Querying to fetch users' name and their todos

### ISSUE THREAD

**Issue by aasthavar** [hasura/learn-graphql#554]
Trying to learn from and follow the tutorial. This is regarding the section **Fetch users and their todos** in [**Queries - Fetching data**](https://hasura.io/learn/graphql/intro-graphql/graphql-queries/)
```
query {
  users {
    name
    todos {
      title
    }
  }
}
```
I got a syntax error - 
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
I couldn't figure out what is the unexpected char, can someone please help me understand? 

Thanks in advance!

**Comment by catalinpit** [comment]
Hello @aasthavar, thank you for reporting this!

I want to let you know that we are actively looking at it. I'll let you know about the progress.

**Comment by praveenweb** [comment]
@aasthavar - Since the above query fetches all users and all their todos, this was hitting the database limit due to thousands of users and their respective todos. 

I have added limits to the response size now. You should now be able to make any arbitrary query and get a response.

Thanks for reporting this. I'm closing this now.
